version: "3.9"

services:

  traefik:
    image: traefik:v2.9.9
    container_name: traefik
    command: --configFile=/etc/traefik/static_conf.yml
    networks: 
      weave:
        ipv4_address: 10.5.0.150
    labels:
      traefik.enable: true
      traefik.http.routers.traefik-dashboard.rule: "Host(`traefik.linode1.your-domain.xd`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.traefik-dashboard.middlewares: authelia
      traefik.http.routers.traefik-dashboard.service: api@internal
      traefik.http.routers.traefik-dashboard.tls.certresolver: letsencrypt
      traefik.http.middlewares.authelia.forwardAuth.address: http://auth.oracle.your-domain.xd:9091/api/verify?rd=https%3A%2F%2Fauth.oracle.your-domain.xd%2F
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      # Consul
      traefik.http.routers.consul-https.service: consul@file
      traefik.http.routers.consul-https.rule: Host(`consul.linode1.your-domain.xd`)
      traefik.http.routers.consul-https.entrypoints: https
      #traefik.http.routers.consul-https.middlewares: authelia
      traefik.http.routers.consul-https.tls.certresolver: letsencrypt 
      # Vault
      traefik.http.routers.vault-https.service: vault@file
      traefik.http.routers.vault-https.rule: Host(`vault.linode1.your-domain.xd`)
      traefik.http.routers.vault-https.entrypoints: https
      #traefik.http.routers.vault-https.middlewares: authelia
      traefik.http.routers.vault-https.tls.certresolver: letsencrypt 
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./acme:/etc/traefik/acme
      - ./static_conf.yml:/etc/traefik/static_conf.yml
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
    
networks:
  weave:
    external: true