accessLog: {}
log:
 level: DEBUG
api:
  insecure: true
  dashboard: true
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml
  docker:
    exposedbydefault: false
metrics:
  prometheus: true
entrypoints:
  http:
    address: :80
  https:
    address: :443
certificatesresolvers:
  letsencrypt:
    acme:
      email: your-email@xd.com
      storage: /etc/traefik/acme/acme.json
      tlschallenge: true