version: '3.9'
services:
  consul-server:
    image: hashicorp/consul:1.14
    container_name: consul-server
    volumes:
      - ./config-server:/consul/config
      - ./data:/consul/data
    ports:
      - 8500:8500
      - 8600:8600
    networks:
      dc1:
        ipv4_address: 10.5.0.2
    restart: always
networks:
  dc1:
    name: dc1
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16