
version: '3.9'
services:
  authelia:
    container_name: authelia
    image: authelia/authelia
    networks: 
      - dmz
    labels:
      traefik.enable: true
      traefik.http.routers.auth-http.entrypoints: http
      traefik.http.routers.auth-http.rule: Host(`auth.oracle.your-domain.xd`)
      traefik.http.routers.auth-http.middlewares: redirect-to-https
      traefik.http.routers.auth-https.rule: Host(`auth.oracle.your-domain.xd`)
      traefik.http.routers.auth-https.entrypoints: https
      traefik.http.routers.auth-https.tls.certresolver: letsencrypt
    environment:
      TZ: 'Europe/Warsaw'
      AUTHELIA_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
    ports:
      - 9091:9091
    volumes:
      - ./users.yml:/config/users.yml:ro
      - ./configuration.yml:/config/configuration.yml:ro
      - ./home:/home
    logging:
      driver: fluentd

networks:
  dmz:
    external: true