version: '3'

services:
  postgres:
    image: postgres:12.12
    environment:
      - POSTGRES_PASSWORD
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      dc1:
        ipv4_address: 10.5.0.10
  postgres-envoy:
    image: consul-envoy
    container_name: postgres-envoy
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/postgres.hcl
      CENTRAL_CONFIG_DIR: /central_config
    command: ["consul", "connect", "envoy", "-sidecar-for", "postgres-id", "-admin-bind", "0.0.0.0:8001" ]
    volumes:
      - ./service_config:/config
      - ./central_config:/central_config
    network_mode: "service:postgres"
  
networks:
  dc1:
    external: true

volumes:
  postgres:
    name: postgres
