default_redirection_url: https://your-domain.xd

authentication_backend:
  file:
    path: /config/users.yml
    watch: false
    search:
      email: false
      case_insensitive: false
    password:
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

session:
  name: authelia_session
  domain: your-domain.xd
  same_site: lax
  secret: F-JaNdRgUkXp2s5v
  expiration: 1h
  inactivity: 5m
  remember_me_duration:  1M

storage:
  encryption_key: a_very_important_secret
  local:
    path: /home/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /home/notification.txt

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 
        - "auth.oracle.your-domain.xd"
      policy: bypass
    ## catch-all
    - domain:
        - "*.oracle.your-domain.xd"
        - "*.linode1.your-domain.xd"
      subject: 
        - "group:admins"
      policy: two_factor
      